ignored-entities:
  - AREA_EFFECT_CLOUD
  # Hanging entities (cannot be spawned without a block)
  - PAINTING
  - LEASH_HITCH
  - ITEM_FRAME
  # No 👀
  - WITHER
  - ENDER_DRAGON
  - GHAST
  - GIANT
  - FIREBALL
items-per-tick: 4
item-spawn-delay: 0
particle-spawn-delay: 4
entity-spawn-delay: 7