name: ${project.name}
version: ${project.version}
main: eu.kennytv.blockdebug.TypeDebugPlugin
author: kennytv
api-version: 1.13 # thanks md_5, very cool

commands:
  start:
    usage: /start <blocks/entities/items>
    permission: blockdebug.start